server:
  port: 8002

spring:
  profiles:
    active: prod # 기본 환경을 prod로 셋팅 local 개발할때는 local로 바꾸세요.

  batch-db:
    datasource:
      driver-class-name: org.mariadb.jdbc.Driver
  campinity-db:
    datasource:
      driver-class-name: org.mariadb.jdbc.Driver

  redis:
    port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  batch:
    job:
      enabled: false   # batch server 실행시켰을 때, 실행되는지 아닌지
    jdbc:
      isolation-level-for-create: default

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG


fcm:
  certification: /demo-core/src/main/resources/firebase/campinity-5ff94-firebase-adminsdk-a0uem-64c6576e75.json
  url: https://fcm.googleapis.com/v1/projects/campinity-5ff94/messages:send
  scope: https://www.googleapis.com/auth/cloud-platform

goCamp:
  url:
    search:
      campsite: http://apis.data.go.kr/B551011/GoCamping/basedList
      image: http://apis.data.go.kr/B551011/GoCamping/imageList
    serviceKey: p70pdHoxT%2Fy5tEkOpbp5jOLMkEYGV%2B8oND1YTMbzMCB9TvNN0cvX9tZSTnO0JV1W6BJk3z9Hq0FgrWDYTovevw%3D%3D

custom:
  path:
    upload-images: '/var/lib/images'