server:
  port: 8003

spring:
  profiles:
    active: prod # 기본 환경을 prod로 셋팅 local 개발할때는 local로 바꾸세요.

  hikari:
    connectionTimeout : 30000
    maximumPoolSize : 30
    maxLifeTime : 97
    poolName : HikariCP
    readOnly : false

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        type:
          preferred_uuid_jdbc_type: CHAR
    #    show_sql: true #show sql
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jwt:
    key: service-key
    live:
      atk : 12096000000 # 2WN
      rtk : 12096000000  #2주
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  redis:
    host: redis_boot
    port: 6379
    password: campinity1308!

logging:
  config: classpath:log4j2.yml
  level:
    org:
      springframework:
        web:
          socket:
            messaging:
              WebSocketMessageHandler: TRACE
        messaging:
          simp:
            user:
              SimpUserRegistry: TRACE
            stomp:
              StompDecoder: TRACE
              StompEncoder: TRACE

  certification: firebase/campinity-5ff94-firebase-adminsdk-a0uem-64c6576e75.json
  url: https://fcm.googleapis.com/v1/projects/campinity-5ff94/messages:send
  scope: https://www.googleapis.com/auth/cloud-platform

goCamp:
  url:
    search:
      campsite: http://apis.data.go.kr/B551011/GoCamping/basedList
      image: http://apis.data.go.kr/B551011/GoCamping/imageList
    serviceKey: A8ooqts7IHFPYficmW%2BDAWnazQPpJnk6MQO%2Bp0hqcBD6lTlv1IoFeGe%2F%2Bu5K%2BWgrxJh2gUrF8YapUodyOkwowA%3D%3D

custom:
  path:
    upload-images: '/var/lib/images'